kind: VirtualClusterInstance
apiVersion: management.loft.sh/v1
metadata:
  name: flux-vc2
  namespace: p-vcluster-flux-demo
spec:
  displayName: Flux vCluster Two
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    access:
      defaultClusterRole: view
      rules:
        - teams:
            - loft-admins
          clusterRole: cluster-admin
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.26.0
      values: |
        sync:
          toHost:
            ingresses:
              enabled: true

        controlPlane:
          coredns:
            enabled: true
            embedded: true
          backingStore:
            etcd:
              embedded:
                enabled: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata:
        annotations:
          field.cattle.io/projectId: local:p-jclhq
        labels:
          field.cattle.io/projectId: p-jclhq
      objects: {}
  clusterRef:
    cluster: loft-cluster
  access:
    - name: instance-access
      verbs:
        - create
        - use
        - get
      subresources:
        - logs
        - kubeconfig
      teams:
        - api-framework
        - loft-admins
  networkPeer: true
