apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-vcluster-internal-argocd
  namespace: argocd
spec:
  generators:
    - pullRequest:
        github:
          appSecretName: loft-demo-org-cred
          labels:
            - create-prvcluster
          owner: loft-demos
          repo: november-app
        requeueAfterSeconds: 30
        template:
          metadata: {}
          spec:
            destination: {}
            project: ''
  template:
    metadata:
      name: november-app-pr-{{number}}
    spec:
      destination:
        name: in-cluster
        namespace: p-api-framework
      info:
        - name: PRvCluster Argo CD URL
          value: https://argocd-november-app-pr-{{number}}.us.demo.dev
        - name: GitHub PR
          value: https://github.com/loft-demos/november-app/pull/{{number}}
      project: default
      source:
        kustomize:
          namePrefix: november-app-pr-{{number}}-
          patches:
            - patch: |-
                - op: replace
                  path: /spec/prNumber
                  value: '{{number}}'
              target:
                kind: PullRequestEnvironment
                name: vcluster
        path: vcluster-use-cases/argocd-vcluster-pull-request-environments/internal/kustomize
        repoURL: https://github.com/loft-demos/november-app.git
        targetRevision: '{{head_sha}}'
      syncPolicy:
        automated:
          selfHeal: true
